### ISSUE TITLE
error building fits_web_ql (ubuntu 18 cloud vm with no assosiated GPU)

### ISSUE THREAD

**Issue by alitimer** [jvo203/fits_web_ql#2] opened 2019-03-01 02:54 UTC
### Not sure about this error; may I know your advise?

`
error: failed to run custom build command for `libvpx-native-sys v4.0.7`
process didn't exit successfully: `/home/ubuntu/astronomy/fits_web_ql/target/release/build/libvpx-native-sys-d9495fe5b1fec0e1/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"vpx\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by alitimer** [comment] 2019-03-01 06:50
Define `LD_LIBRARY_PATH` to point out the shared object file
`export LD_LIBRARY_PATH=../../Downloads/libyuv/build:$LD_LIBRARY_PATH`
`export LD_LIBRARY_PATH=../../Downloads/x265_3.0/build:$LD_LIBRARY_PATH`

**Comment by jvo203** [comment] 2019-03-08 10:59
Is this still an open issue? Such errors would usually be caused by a non-standard location of the manually-compiled/locally-installed libvpx, in which case playing with the following environment variables (ideally set in .bashrc etc.) should solve the problem:

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

**Comment by skitaeff** [comment] 2019-03-08 12:08
No, it is no longer an issue. You can close it. Thanks, Slava

Sent from my iPhone

On 8 Mar 2019, at 10:59 am, jvo203 <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still an open issue? Such errors would usually be caused by a non-standard location of the manually-compiled/locally-installed libvpx, in which case playing with the following environment variables (ideally set in .bashrc etc.) should solve the problem:

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

**Comment by alitimer** [comment] 2019-03-08 12:26
Thanks for your reply; already addressed the LD_LIBRARY_PATH and PKG_CONFIG_PATH, however stuck in the above error. Not sure about the VM because it's working on native Ubuntu and this happens on a cloud vm!

**Comment by jvo203** [comment] 2019-03-08 15:13
After correcting the LD_LIBRARY_PATH and PKG_CONFIG_PATH, if the issue still persists you could issue "cargo clean" from within the fits_web_ql folder and then re-try cargo build. There may be some stale settings remaining in a cargo cache from previous failed cargo build runs, which the "cargo clean" command should resolve. As per Slava's comment, I will close this issue then.

**Closed as completed by jvo203** 2019-03-08 15:13 UTC

**Comment by jvo203** [comment] 2019-03-09 01:24
An additional comment: FITSWebQL Fe (Rust edition) is known to work well on Intel Clear Linux running on Microsoft Azure cloud (tested last year). If you are feeling adventurous you could give it at try. Here are the extra steps needed to get it to work on Intel Clear Linux:

sudo swupd bundle-add dev-utils c-basic rust-basic

manual yasm 1.3.0 compile/install from source

manual openssl compile/install from source (plus copy the certificates from /etc/... to /usr/local/...)

tcl from source (tcl-basic does not provide tcl.h)

NGINX reverse proxy

launching:	sudo nginx

configuration:	cat /etc/nginx/nginx.conf 
worker_processes  4;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile      on;
    aio           on;
    tcp_nopush    on;
    directio      8m;

    access_log    syslog:server=unix:/dev/log;

	map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

	upstream websocket {
        server 127.0.0.1:8080;
    }

	server {
        listen 80 default;
        location / {
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header   Host             $host;

            proxy_pass http://127.0.0.1:8080/;

        }

		location /fitswebql/websocket {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }

	

    #include /etc/nginx/conf.d/*.conf;
}
